### PR TITLE
Fix schema caching for multi-schema workspaces

### LINKED ISSUE #178: Schema caching broken for multiple schemas since 2.1.0
**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

The current schema caching implementation (added in #137) currently prevents a multi-project (aka multi-schema) configuration as it keys caching on the eslint configuration, whereas schema resolution is dependent on the path to the GraphQL file being linted.

We can fix this by caching the schemas and the graphql configuration (along with the other cached elements) and instead of returning the cache entry directly, compose the cache hit into a result based on the file path being linted.

### PR DESCRIPTION
**Pull request by patsissons**
TODO:

- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests pass
- [x] Update CHANGELOG.md with your change
- [ ] If this was a change that affects the external API, update the README

**Pull Request Labels**

- [ ] feature
- [x] blocking
- [ ] docs

resolves #178

### CODE REVIEW

**Comment by BPScott** [comment]
Ping @stubailo, as part of your recent flurry of updates, would it be possible to take a look at this? It's currently blocking a project of mine and @patsissons' from updating to the latest version.

**Comment by stubailo** [comment]
@BPScott right now I have 3 goals:

1. Fix the `required-field` rule to always work when fragments are involved #199 
2. Add an auto-fix for that rule
3. Make sure schema loading is reliable, especially in the case of schemas changing while your editor is open

That said, let me take a look

**Comment by stubailo** [comment]
It seems like a pretty safe change 🤔 can you rebase and I'll try to release it?

**Comment by stubailo** [comment]
(Also that will ensure the build passes)
(Also sorry I moved some of the tests around, so hope it's not too bad)

**Comment by patsissons** [comment]
no rebase conflicts 👍

**Comment by stubailo** [comment]
🎉

**Comment by stubailo** [comment]
published in 3.0.1 - can you tag me on any relevant issues to be closed?

**Comment by patsissons** [comment]
#178 should be closed now thanks to `resolved` keyword in the description.

**Pull request merged**
