### PR TITLE
fix bugs in EnumValue

### PR DESCRIPTION
**Pull request by NeoPhi**
TODO:

- [x] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests pass
- [x] Update CHANGELOG.md with your change
- [x] If this was a change that affects the external API, update the README

### CODE REVIEW

**Comment by jnwng** [comment]
thanks @NeoPhi, just confirming that this is the best way to get this information for enums. im looking into the upstream issues with `graphql-import` that are showing up in travis

**Comment by NeoPhi** [comment]
Based on how https://github.com/graphql/graphql-js/blob/master/src/utilities/findDeprecatedUsages.js#L49 is implemented, I've not found another way to get access to `getEnumValue` given that https://github.com/graphql/graphql-js/blob/master/src/validation/validate.js#L97 doesn't expose that utility function nor does it export  `typeInfo`.

**Comment by jnwng** [comment]
oh sorry @NeoPhi i had meant that i was confirming that "yes, this is the best way to do this". im figuring out what to do about upstream dependencies that don't match our engine support before merging / releasing this.

**Comment by jnwng** [comment]
finally — figured out what was going on in an upstream dependency that was being triggered here. turns out the Travis test runner uses `npm` instead of `yarn`, but in this case that was actually good as it revealed that we had dependencies that didn't work properly in Node v4/v5.

**Pull request merged**
