### PR TITLE
Add Named Operations Validation Rule to README

### PR DESCRIPTION
**Pull request by gauravmk**
Feel free to make whatever edits you want to clarify the rule

### CODE REVIEW

**Comment by jnwng** [comment]
interesting - now that this doc is available, i wonder if we even need to have the `schema` to lint whether or not operations have names...

**Comment by gauravmk** [comment]
yea, you don't actually need it, but it made the implementation a lot uglier, since graphqls validate function requires a schema even the rule doesn't depend on it. `validate(schema, ast, validators)` is how it's called. I figured especially as people expand with new rules, most of them will require a schema so I lumped it into the "default options" list here: https://github.com/apollographql/eslint-plugin-graphql/blob/master/src/index.js#L44

**Comment by stubailo** [comment]
Hmmm, the question is - would we want people to use this package to not actually do validation but only style linting?

**Comment by jnwng** [comment]
possibly, my hesitation here is just that that particular rule doesn't need a schema and i figure its just unnecessary.

in any case, re-using the reference to the schema is cheap, so until something like #4 is addressed (getting schemas from remote) then this seems fine to merge as-is.

**Pull request merged**
